### PR TITLE
VRS ID Annotator Module

### PR DESCRIPTION
**Pull request by Nitram36**

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
`ga4gh` library seems to be needed, but `pip install ga4gh` failed. It seems that `ga4gh` and `ga4gh-schemas` are based on Python 2. How did you make it to run with Python 3?

**Comment by Nitram36** [comment]
Hi Rick, this module needs the ga4gh extras package so would need to do `pip install 'ga4gh.vrs[extras]'` with the quotation marks around the package name. Then I had to do `pip uninstall psycopg2 psycopg2-binary` and finally `pip install psycopg2-binary`

**Comment by rkimoakbioinformatics** [comment]
Ah indeed. Installing psycopg2 is having a problem in M1 MacBook, but this is Ok for now. I'll come back after some tests.

**Comment by rkimoakbioinformatics** [comment]
Can you ask the ga4gh.vrs dev team (github issues, etc) about installing the package? I tried Python 3.10 and still got the error. So far. I have got the error on Ubuntu and M1 MacBook. The error from `pip install ga4gh.vrs[extra]` was

```
Collecting psycopg2 (from hgvs>=1.4->ga4gh.vrs[extras])
  Using cached psycopg2-2.9.9.tar.gz (384 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-h94y3hs9/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-h94y3hs9/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-h94y3hs9/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-h94y3hs9/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-h94y3hs9/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Nitram36** [comment]
Have you tried `pip uninstall psycopg2 psycopg2-binary` followed by `pip install psycopg2-binary` ?

**Comment by rkimoakbioinformatics** [comment]
In my Ubuntu machine, there was a missing system-level library. Please take a look at https://stackoverflow.com/questions/11618898/pg-config-executable-not-found. 

Can you add to the .md file something about needing to install libpq-dev (Ubuntu), libpqxx-devel (Fedora), brew install postgresql and brew link postgresql (MacOS)?

**Comment by rkimoakbioinformatics** [comment]
Finally ran it! It seems that indels did not get VRS ID. See below.
```
chr12|25245378|-|A|
chr12|25245378|-|C|
chr12|25245384|A|T|ga4gh:VA.NltOdcGzm7cZBcBAZKJSnVU2JIUxtDZF
chr1|22563636|A|T|ga4gh:VA.UJkGiwHL6kxZgfp051O245_mEaMc1eX0
chr1|22586480|C|A|ga4gh:VA.Wj_f4zP-2bMZpsgQP-QKiMytLTCvTB4t
chr1|226064352|A|T|ga4gh:VA.hyCfaWUmRdoaGuDgHCElvB2iCc0u-tvk
chr1|235181776|G|C|ga4gh:VA.Gmh3hhrLd6FQdCnxsr1hXJdApQh_7P56
```
Is this limitation of ga4gh.vrs? I think the following error happened with indels.
```
  File ".../oakvar/oakvar/lib/base/annotator.py", line 530, in process_file
    output_dict = self.annotate(input_data)
  File ".../oakvar-modules/annotators/vrs_id/vrs_id.py", line 30, in annotate
    vrs_allele = tlr.translate_from(allele, 'beacon') # translate to vrs format
  File ".../ga4gh/vrs/extras/translator.py", line 85, in translate_from
    raise ValueError(f"Unable to parse data as {fmt} variation")
ValueError: Unable to parse data as beacon variation
```
Can you take a look into this?

**Comment by Nitram36** [comment]
Great! I can add those fixes to the .md file. Yes I noticed that it would only add vrs id to single nucleotide variants and not other types of variant. I mentioned in the .md that this was for annotating SNVs but I will look to see if vrs offer a way to annotate other variants. Otherwise I can alter the .py file so that a vrs id is only computed for SNVs and other variants will be ignored to prevent the error from occurring.

**Comment by Nitram36** [comment]
After you installed libpq-dev on your Ubuntu machine did you still need to install psycopg2-binary to get the vrs_id module to work?

**Comment by rkimoakbioinformatics** [comment]
It seems that uninstalling/installing psycopg2 and psycopg2-binary is not necessary anymore, after installing libpq-dev.

By the way, I just did a test run and got an error message:
```
2023/11/03 09:06:20 oakvar.vrs_id        Traceback (most recent call last):
  File "/home/rick/mambaforge/envs/py311/lib/python3.11/site-packages/oakvar/lib/base/annotator.py", line 570, in process_file
    output_dict = self.annotate(input_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Git/oakvar-modules/annotators/vrs_id/vrs_id.py", line 30, in annotate
    vrs_allele = tlr.translate_from(allele, 'beacon') # translate to vrs format
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rick/mambaforge/envs/py311/lib/python3.11/site-packages/ga4gh/vrs/extras/translator.py", line 85, in translate_from
    raise ValueError(f"Unable to parse data as {fmt} variation")
ValueError: Unable to parse data as beacon variation
```
It seems that the error occurs with insertion and deletion, but not with SNVs.

**Comment by rkimoakbioinformatics** [comment]
Thanks. `brew install postgresql` fixed the problem I was having. Good to see it mentioned in the md file.

**Pull request merged**
