### PR TITLE
final python script, yml, gen

### PR DESCRIPTION
**Pull request by gehadkamel**

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
Thanks.

- dbgap.sqlite: please use `trait_uid` in `dbgap` table instead of `trait` text, as in `create table dbgap (trait_uid integer, rsid integer, ...)` and `create table trait (uid integer, trait text)`. This way, unnecessary repetition of `trait` text will be avoided, saving disk space.
- dbgap.py: Use `join` to get trait text, as in `select ... from dbgap inner join trait on dbgap.trait_uid = trait.uid ...`.

**Comment by rkimoakbioinformatics** [comment]
As for `join`, see https://www.sqlitetutorial.net/sqlite-join/ for examples.

**Comment by rkimoakbioinformatics** [comment]
Thanks. It seems that dbgap.py and dbgap_sqlite.py do not match in terms of column names. For example, `trait_uid` and `trait` and `uid`. Can you take a look?

Also, please use `rsid` instead of `snp` in secondary_data["dbsnp"][0]["rsid"].

**Comment by gehadkamel** [comment]
I updated the script , may you have a check on it?

**Comment by rkimoakbioinformatics** [comment]
Thanks. A few things:

- Column name mismatch: between the generated database column names and dbgap.py's SQL query, some column names do not match.
- In dbgap.py, `rsid` from secondary_input is a `str` such as `rs2873832`, while the rsid in dbgap.sqlite has `int` for rsid. The `str` rsid should be converted to `int` by removing the `rs` and `int` method, and then compared to the database.
- In dbgap.py, the SQL query has a bug with `JOIN`.

**Pull request merged**
