### PR TITLE
G input

### PR DESCRIPTION
**Pull request by gehadkamel**

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
- I got `NameError: name 'seq1' is not defined`. `def seq1` definition does not have `self`. Did you check the output of `ov run` and see that pmkb output was correctly written?
- `pypache` should not be included in the repo as it is generated in users' system automatically.
- `data` folder should not be included in the repo as it can be large. Please use attachment in pivotal or something like Google drive.

**Comment by gehadkamel** [comment]
Yea I left the BioPython package in my local script `oakvar_modules/annotators/pmkb/` directory that was why it ran fine  with me. Any way I defined the function outside the class as I do not intend to use it as a method later on. Secondly, I revised the populated columns in the output csv file and it was populated right. I will cross my fingers that this time it will work on yours. 

Finally, I will remove the data and pycache folder

**Comment by rkimoakbioinformatics** [comment]
If you run `ov run exampleinput -a pmkb --endat annotator --clean`, do you get `exampleinput.pmkb.var` file? Does it have annotation? This file I get has no annotation.

**Comment by rkimoakbioinformatics** [comment]
Please check base__uid 63. Its amino acid change is p.Glu3ValfsTer3, which is at codon 3, but it matched with _codon:12,13,61,117,146:_any:_any:_any, which should not happen, it seems?

**Pull request merged**
