### PR TITLE
MAF Reporter PR

### PR DESCRIPTION
**Pull request by IulianIV**

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
Thanks. If a job was not run with the annotators necessary for MAF columns, ov report -t maf currently gives errors. For example, ncbigene, dbsnp, ensembl_regulatory_build, etc. To solve this, please implement the following:

1. Add `requires` field to mafreporter.yml, such as:
```
requires:
- ncbigene
- dbsnp
- ensembl_regulatory_build
- <Other needed modules>
```

2. In `setup` method of mafreporter.py, check annotator-specific columns in the input database and if any needed column is missing print a warning message listing the missing annotators, but go ahead and make a MAF file with empty values for the columns with missing annotators. Columns in a table can be known with 
```
import sqlite3
conn = sqlite3.connect("db.sqlite")
c = conn.cursor()
c.execute("pragma table_info (variant)") # variant table, for example
c.fetchall()

[(0, 'base__uid', 'INTEGER', 0, None, 0), (1, 'base__chrom', 'TEXT', 0, None, 0), (2, 'base__pos', 'INTEGER', 0, None, 0), (3, 'base__pos_end', 'INTEGER', 0, None, 0), (4, 'base__ref_base', 'TEXT', 0, None, 0), (5, 'base__alt_base', 'TEXT', 0, None, 0), (6, 'base__tags', 'TEXT', 0, None, 0), (7, 'base__coding', 'TEXT', 0, None, 0), (8, 'base__hugo', 'TEXT', 0, None, 0), (9, 'base__transcript', 'TEXT', 0, None, 0), (10, 'base__so', 'TEXT', 0, None, 0), (11, 'base__cchange', 'TEXT', 0, None, 0), (12, 'base__achange', 'TEXT', 0, None, 0), (13, 'base__exonno', 'INTEGER', 0, None, 0), (14, 'base__all_mappings', 'TEXT', 0, None, 0), (15, 'base__refseq', 'TEXT', 0, None, 0), (16, 'clinvar__sig', 'TEXT', 0, None, 0), (17, 'clinvar__disease_refs', 'TEXT', 0, None, 0), (18, 'clinvar__disease_names', 'TEXT', 0, None, 0), (19, 'clinvar__rev_stat', 'TEXT', 0, None, 0), (20, 'clinvar__id', 'TEXT', 0, None, 0), (21, 'clinvar__sig_conf', 'TEXT', 0, None, 0), (22, 'original_input__chrom', 'TEXT', 0, None, 0), (23, 'original_input__pos', 'INTEGER', 0, None, 0), (24, 'original_input__pos_end', 'INTEGER', 0, None, 0), (25, 'original_input__ref_base', 'TEXT', 0, None, 0), (26, 'original_input__alt_base', 'TEXT', 0, None, 0), (27, 'tagsampler__genotypes', 'TEXT', 0, None, 0), (28, 'tagsampler__numsample', 'INTEGER', 0, None, 0), (29, 'tagsampler__samples', 'TEXT', 0, None, 0), (30, 'tagsampler__tags', 'TEXT', 0, None, 0)]
```

**Comment by IulianIV** [comment]
Hey, I added a new commit. The new commit checks existing annotators inferred from existing columns and compare them to a list of required annotators. If they are missing then a log warning message is thrown with a list of the missing annotators and a notice that their dependent columns will be set as empty.

**Comment by rkimoakbioinformatics** [comment]
Thanks. Please download https://drive.google.com/file/d/1h2iacwXUYeZi9rUtwNsntYLWIe-u0EBX/view?usp=share_link (.sqlite file) and try 

`ov report testinput.sqlite -t maf --module-options mafreporter.type=somatic`
and
`ov report testinput.sqlite -t maf --module-options mafreporter.type=protected`

`all_effects` and `Consequence` columns are different in the two files. The content is the same, but the order of sequence ontology terms are different. I think one is sorted and the other is not. Can you check about it? Ideally, sorted ones will be good.

**Comment by IulianIV** [comment]
Hi, I changed the code. should be fine now. The bug was in the `write_consequence` method which handles the `Consequences` column which in the end is used in the `all_effects` column. There was a `set()` type variable used to make values unique from `base__all_mappings` - I changed the code to keep unique values but also maintain order.

**Pull request merged**
