### PR TITLE
Fhir reporter

### PR DESCRIPTION
**Pull request by AkRampersad**
had a minor problem with the forks on my end. They are fixed. This pull request should address the points brought up in the previous pull request.  Here are the request for reference. 

fhirreporter.py

    It seems to hold all variants in memory and then write at once. This can be a problem with a big result data. However, let's wait and see if this becomes a problem for now.
    savepath from "-fhir.json" to ".fhir.json" and from "oakvar_result.json" to "oakvar_result.fhir.json"

fhirreporter.yml

    "{run_name}" to "{run_name}.fhir.json"
    developer email: change the order so that the order matches that of names.
    version to 0.1.0

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
**fhirreporter.py**

- Does a FHIR file can have many patients? If not, a FHIR file should be generated for each patient. Holding a collection of FHIR bundles, one bundle for patient, and writing those into different files at the end may be needed? In write_table_row, row["tagsampler__samples"] will have the samples which contain the given variant, delimited by ";" I think. Thus, row["tagsampler__samples"].split(";") will give a list of the samples which have the variant. Then, the variant can be added to the bundles for the patients.

- patient_name: primary_transcript from info table is not a sample's name, so probably not a good choice for patient_name. If it is a sample name, then `sample` table's base__sample_id has all the samples of the result data. Getting a unique list of samples with something like "select unique(base__sample_id) from sample" and then making a separate bundle for each sample may be needed.

- self.end() method is call the very end. `def end(self)` can be defined and writing JSON files can be done there. This way, checking if the number of variants in the bundle is the same as that in the database in write_table_row is not necessary.
- I thought that a bundle needs a UUID? Just checking.
- Regarding each entry's UUID, please use "mapper" value from the same info table to self.str_id as well. 
- Regarding the below part,
```
id_maker = (self.str_id) + str(100 * self.counter)
id = self.uuid_maker(id_maker + self.str_id)
```
since the UUID is for each variant with all the annotations and the information on what annotations were performed is stored in self.str_id, the variant's identification should be added instead of 100 * self.counter. Thus, something like
```
id_maker = self.str_id + f"{row['base__chrom'] + row['base__pos'] + row['base__ref_base'] + row['base__alt_base']}"
```
can work.

**Comment by rkimoakbioinformatics** [comment]
Thanks.

- `fhirreporter.yml`: please add `pypi_dependency` field and add all PyPI library dependencies (fhir.resources, etc).
- `fhirreporter.py`:
  - remove any debug print lines (line 108 caused an error, for example).
  - Line 166 self.counter caused an error. Not needed?
  - Download https://drive.google.com/file/d/1h2iacwXUYeZi9rUtwNsntYLWIe-u0EBX/view?usp=sharing (sqlite file) and try `ov report testinput.sqlite -t fhir`. On my system, it causes the following error.
```
023/07/18 09:12:59 oakvar               Generating fhirreporter report...
2023/07/18 09:12:59 fhirreporter         started: Tue Jul 18 09:12:59 2023
2023/07/18 09:12:59 fhirreporter         started fhirreporter (fhirreporter)
['no-sample']
no-sample
this variant is found in samples ['no-sample']
Traceback (most recent call last):
  File "/Users/rick/oxv/oakvar/oakvar/lib/base/reporter.py", line 429, in run
    await self.write_data(
  File "/Users/rick/oxv/oakvar/oakvar/lib/base/reporter.py", line 517, in write_data
    self.write_row_with_samples_separate_or_not(datarow)
  File "/Users/rick/oxv/oakvar/oakvar/lib/base/reporter.py", line 548, in write_row_with_samples_separate_or_not
    self.write_table_row(self.get_extracted_row(datarow))
  File "/Users/rick/oxv/oakvar-modules-public/reporters/fhirreporter/fhirreporter.py", line 179, in write_table_row
    obs_row = Observation(
  File "/Users/rick/miniforge3/envs/py39/lib/python3.9/site-packages/fhir/resources/core/fhirabstractmodel.py", line 105, in __init__
    BaseModel.__init__(__pydantic_self__, **data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Observation
subject -> __root__
  Value is expected from the instance of <class 'fhir.resources.reference.Reference'>, but got type <class 'list'> (type=value_error)
Traceback (most recent call last):
  File "/Users/rick/miniforge3/envs/py39/bin/ov", line 8, in <module>
    sys.exit(main())
  File "/Users/rick/oxv/oakvar/oakvar/__main__.py", line 204, in main
    handle_exception(e)
  File "/Users/rick/oxv/oakvar/oakvar/__main__.py", line 181, in handle_exception
    raise e
  File "/Users/rick/oxv/oakvar/oakvar/__main__.py", line 196, in main
    ret = func(args)
  File "/Users/rick/oxv/oakvar/oakvar/cli/__init__.py", line 25, in change_args_for_cli
    ret = func(args)
  File "/Users/rick/oxv/oakvar/oakvar/cli/report.py", line 7, in cli_report
    return report(args)
  File "/Users/rick/oxv/oakvar/oakvar/cli/__init__.py", line 46, in run_cli_func
    handle_exception(e)
  File "/Users/rick/oxv/oakvar/oakvar/__main__.py", line 181, in handle_exception
    raise e
  File "/Users/rick/oxv/oakvar/oakvar/cli/__init__.py", line 39, in run_cli_func
    ret = func(args, **kwargs)
  File "/Users/rick/oxv/oakvar/oakvar/cli/report.py", line 26, in report
    ret = report(**args)
  File "/Users/rick/oxv/oakvar/oakvar/api/__init__.py", line 396, in report
    handle_exception(e)
  File "/Users/rick/oxv/oakvar/oakvar/api/__init__.py", line 469, in handle_exception
    raise e
  File "/Users/rick/oxv/oakvar/oakvar/api/__init__.py", line 384, in report
    response_t = loop.run_until_complete(reporter.run())
  File "/Users/rick/miniforge3/envs/py39/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/Users/rick/miniforge3/envs/py39/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/rick/miniforge3/envs/py39/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/rick/oxv/oakvar/oakvar/lib/base/reporter.py", line 454, in run
    raise e
  File "/Users/rick/oxv/oakvar/oakvar/lib/base/reporter.py", line 429, in run
    await self.write_data(
  File "/Users/rick/oxv/oakvar/oakvar/lib/base/reporter.py", line 517, in write_data
    self.write_row_with_samples_separate_or_not(datarow)
  File "/Users/rick/oxv/oakvar/oakvar/lib/base/reporter.py", line 548, in write_row_with_samples_separate_or_not
    self.write_table_row(self.get_extracted_row(datarow))
  File "/Users/rick/oxv/oakvar-modules-public/reporters/fhirreporter/fhirreporter.py", line 179, in write_table_row
    obs_row = Observation(
  File "/Users/rick/miniforge3/envs/py39/lib/python3.9/site-packages/fhir/resources/core/fhirabstractmodel.py", line 105, in __init__
    BaseModel.__init__(__pydantic_self__, **data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Observation
subject -> __root__
  Value is expected from the instance of <class 'fhir.resources.reference.Reference'>, but got type <class 'list'> (type=value_error)
^Czsh: terminated  ov report testinput.sqlite -t fhir
```

**Comment by rkimoakbioinformatics** [comment]
- I notice that there are ref_base and alt_base in the FHIR report. Please add `chrom` and `pos` information as well.
- Can we add base__so (sequence ontology)?
- base__cchange and base__achange as well.

**Comment by rkimoakbioinformatics** [comment]
base__cchange is cDNA change and thus should not be included in the same category with base__achange. Can you find a loinc code for cDNA change?

**Comment by AkRampersad** [comment]
there is no specific loinc code for cDNA change. I have found an SO term for sequence_comparison (SO:0002072) and a term for cDNA (SO:0000756) . I believe one of these can work if you deem it so (there doesn't need to a base__so for this, its just a coding system to identifiy that the fhir observation component represents a cDNA or sequence comparison). Please let me know and I will implement it asap.

**Comment by rkimoakbioinformatics** [comment]
For base__cchange, please use https://loinc.org/48004-6/.

**Comment by rkimoakbioinformatics** [comment]
Regarding base__pos and base__end_pos, I think https://loinc.org/81247-9/panel#76678 can be used.

Actually, please take a look at https://loinc.org/81247-9. I think we can add the following:

- dbSNP: if dbsnp__rsid is present.

**Comment by AkRampersad** [comment]
I have added the base__cchange component sorry about that I didn't find the term when I searched up cDNA.  

I already have the base__pos and base__end_pos component using that same LOINC code.  The components should be in the files produced (I have check it by searching the document for 81254-5 and it appears.) 

Where is the dbsnp__rsid I can not find in the exampleinput sql.

For the LOINC code,  there are many dbSNP codes  depending on the panel the dbSNP is under. For example the code for a dbSNP has a code "[81255-2](https://loinc.org/81247-9/panel#76672)" whereas a dbSNP under a Discrete genetic variant panel has a code of "[81255-2](https://loinc.org/81247-9/panel#80113)" I will compile a some notes on the different panel types in the mean time.

**Comment by rkimoakbioinformatics** [comment]
- Please use Ensembl transcript instead of RefSeq.
- Use comp_sne only and remove comp_pos unless comp_pos mandatory.
- If comp_so is empty, there is no need to show comp_change and comp_cchange.
- Add https://loinc.org/81247-9/panel#76687 for base__hugo.
- Add https://loinc.org/81247-9/panel#76692 for base__transcript.

With that said, the above will show the mapping on only the primary transcript. There are more mappings for an input variant in base__all_mappings. Ideally, we want to show all the mappings.

Is it possible to, for one chrom, start-end, ref_base, and alt_base, show multiple sets of [hugo, transcript, so, achange, cchange]?

**Comment by rkimoakbioinformatics** [comment]
In fhirreporter.py, check for `self.module_options["include_all_transcripts"]`. If it is "true" (it will be a str), include `base__all_mappings` in the output. If not, skip it as it does now. CLI can be used in the following way to give the option:

`ov report exampleinput.sqlite -t fhir --module-options include_all_transcripts=true`

**Comment by rkimoakbioinformatics** [comment]
Thanks. Quite close to completion. A few things:

- There are variants that are in multiple samples. In such variants, samples will be delimited by a comma, as in `s0,s1`. Currently, files like `exampleinput__s0,s1.primary.fhir.json` are produced. `s0,s1` should be split into [s0, s1] and the same variant should be included in both `exampleinput__s0.primary.fhir.json` and `exampleinput__s1.primary.fhir.json`.
- If achange is None, `48006-1`'s text should be empty. Currently, something like `ENST00000327946.1:None` is written.
- `DNA change` for Ensembl and RefSeq transcripts: One has a loinc code and the other does not? Also, `DNA change (c.HGVS)` vs `DNA change(c.HGVS)` (space difference)?
- In `...all.fhir.json`, transcripts, cDNA change, amino acid change, and sequence ontology are sequentially listed without grouping by transcript. They should be grouped by transcript somehow, so that a transcript, cDNA on that transcript, amino acid change on that transcript, and sequence ontologies on that transcript should be a sort of one unit. Is this possible?

**Comment by rkimoakbioinformatics** [comment]
Still `exampleinput__s0,s1.primary.fhir.json` is produced. self.samples should be made with split as well.

**Comment by rkimoakbioinformatics** [comment]
Thanks.
- It seems that position is not added?
- sequenceontology.org resource: Can you ask the FHIR team if LOINC code exists for this? It seems that missense_variant, etc. in base__so should be in valueCodeableConcept? For example,
```
          {
            "code": {
              "coding": [
                {
                  "system": "http://sequenceontology.org",
                  "code": "SO:0001583",
                  "display": "missense_variant"
                }
              ]
            }
          },
         {
            "code": {
              "coding": [
                {
                  "system": "http://sequenceontology.org",
                  "code": "SO:0002012",
                  "display": "start_lost"
                }
              ]
            }
          },
```
Can it be something like the following?
```
{
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "?????",
        "display": "?????????????"
      }
    ]
  },
  "valueCodeableConcept": {
    "coding": [
      {
        "system": "http://sequenceontology.org",
        "code": "SO:0001583",
        "display": "missense_variant"
      },
      {
        "system": "http://sequenceontology.org",
        "code": "SO:0002012",
        "display": "start_lost"
      }
    ]
  }
}
```

**Comment by AkRampersad** [comment]
Hello I have looked into that but the LOINC codes for sequence ontologies (and many genomic report components such as prognostic implication, functional effect, repeat-motif) do not exist yet. Instead they use this site (http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/tbd-codes-cs) as a code system and have a code for sequence ontology (functional effect). This would be no problem to add if its deemed better.

**Comment by rkimoakbioinformatics** [comment]
The fictional effect seems to be the right one to use. Please update the code using it.

**Comment by rkimoakbioinformatics** [comment]
Thanks. 
- base__pos value is not being written.
```
          {
            "code": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "92822-6"
                }
              ]
            },
            "valueCodeableConcept": {
              "coding": [
                {
                  "system": "http://loinc.org",
                  "code": "LA30102-0",
                  "display": "1-based character counting"
                }
              ]
            }
          },
```
I wonder https://loinc.org/81250-3/panel#76662 is where we can write something like `chr1:g.87384789A>T`? The above seems correct since it specifies the coordinate system. I don't see a term for the position itself. 
- `Cytogenic (chromosome) location`: This seems to be about https://medlineplus.gov/genetics/understanding/howgeneswork/genelocation. If so, since we don't have this information, it should be removed?
- `feature-consequence`: Instead of
```
          {
            "code": {
              "coding": [
                {
                  "system": "http://hl7.org/fhir/uv/genomics-reporting/STU2/CodeSystem-tbd-codes-cs",
                  "code": "feature-consequence"
                }
              ]
            },
            "valueCodeableConcept": {
              "coding": [
                {
                  "system": "http://sequenceontology.org",
                  "code": "missense_variant",
                  "display": "SO:0001583"
                }
              ]
            }
          },
          {
            "code": {
              "coding": [
                {
                  "system": "http://hl7.org/fhir/uv/genomics-reporting/STU2/CodeSystem-tbd-codes-cs",
                  "code": "feature-consequence"
                }
              ]
            },
            "valueCodeableConcept": {
              "coding": [
                {
                  "system": "http://sequenceontology.org",
                  "code": "start_lost",
                  "display": "SO:0002012"
                }
              ]
            }
          },
```
is the below possible (I meant the below)?
```
          {
            "code": {
              "coding": [
                {
                  "system": "http://hl7.org/fhir/uv/genomics-reporting/STU2/CodeSystem-tbd-codes-cs",
                  "code": "feature-consequence"
                }
              ]
            },
            "valueCodeableConcept": {
              "coding": [
                {
                  "system": "http://sequenceontology.org",
                  "code": "missense_variant",
                  "display": "SO:0001583"
                },
                {
                  "system": "http://sequenceontology.org",
                  "code": "start_lost",
                  "display": "SO:0002012"
                }
              ]
            }
          },
```
Also, `code` and `display` values should be swapped.

**Comment by AkRampersad** [comment]
Hello I made a push fixing the position and Sequence ontologies. As for the chromosome position this is an example of this resource taken from the FHIR website (http://build.fhir.org/ig/HL7/genomics-reporting/Observation-SNVexample.json.html)

`
{
      "[code](http://hl7.org/fhir/R4/observation.html#Observation.component.code)" : {
        "[coding](http://hl7.org/fhir/R4/datatypes.html#CodeableConcept#CodeableConcept.coding)" : [
          {
            "[system](http://hl7.org/fhir/R4/datatypes.html#Coding#Coding.system)" : "http://loinc.org",
            "[code](http://hl7.org/fhir/R4/datatypes.html#Coding#Coding.code)" : "48001-2",
            "[display](http://hl7.org/fhir/R4/datatypes.html#Coding#Coding.display)" : "Cytogenetic (chromosome) location"
          }
        ]
      },
      "[valueCodeableConcept](http://hl7.org/fhir/R4/observation.html#Observation.component.value[x])" : {
        "[text](http://hl7.org/fhir/R4/datatypes.html#CodeableConcept#CodeableConcept.text)" : "chrX"
      }
      
      
`

I believe this is different from the link you provided?  At least for this is example it seems so. I could be wrong because its a X chromosome used in the FHIR example (but I don't believe that would change anything?)

**Comment by rkimoakbioinformatics** [comment]
From that example, using chromosome with that resource seems fine. 

I checked the newest code and it seems that with --module-options fhirreporter.all_transcripts=true, base__all_transcripts data is not written, although the file name is correct with all.fhir.json extension. Does it work correctly in your system?

**Comment by rkimoakbioinformatics** [comment]
Seems working fine. Please change the following:
- Version to 1.0.0.
- `pypi_dependency`: remove sqlite3.
- Test: Create a new conda environment with Python 3.8. Install oakvar as well as the PyPI packages defined in `pypi_dependency`. Then, run fhirreporter (ov run or ov report) in that new environment. If there is any missing PyPI dependency, it will err. Add those PyPI packages to `pypi_dependency`.
- Install `ruff` (https://pypi.org/project/ruff/) and correct any linting error (unused variables, etc.).

**Comment by rkimoakbioinformatics** [comment]
I am thinking about the following changes. Let me know if you have a different thought. 

- In primary.fhir.json files, base__transcript, base__so, base__cchange, and base__achange should be included in the resource with a genomic position. Currently, base__transcript and base__so are included.
- In all.fhir.json files, shouldn't the resource with a genomic position, chromosome name, etc. be somehow referenced by the resources with pHGVS, cHGVS, etc?

**Comment by AkRampersad** [comment]
Hello sir,

For the first point regarding primary.fhir.json files. I decided that the
variant profile would only house information that the molecular consequence
could not. Infact upon further inspection I found that the transcript can
be in the molecular consequence. This means that the variant profile would
only have: Ref-allele, Alt-allele, Chromosome Number, Coordinate System,
and Position. The rest of the information (Transcripts, Sequence Ontology,
aa_change,c_change) are in the molecular consequence. Looking at the
molecular consequence profile (
http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-molecular-consequence-definitions.html)
I can not find a position/start-end component.  This way of organization
seems to be the way to use the molecular consequence profile if we are to
use it but I am open to changing it how you see fit.

As for the all.fhir.jsons one way I can reference the variant is to use a
derived from component. I have made a push that implements this derivedfrom
component.

Thank you,
Akash

**Pull request merged**
