### PR TITLE
gwas_catalog files 

### PR DESCRIPTION
**Pull request by zigizolt**

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
Thanks. I'll check.

**Comment by rkimoakbioinformatics** [comment]
1. Please add your information under 
```
developer:
  module:
    name:
    organization:
    email:
    website:
    citation:
  data:
    name:
    organization:
    email:
    website:
    citation:
```
Put your information under `module` and the information of the GWAS Catalog under `data`.

2. .py file has a couple of functions without anything, which cause an error.

3. In the py file, `or_beta` becomes slightly different values after being retrieved from the database, for a mysterious reason. For example, 0.0273 becomes 0.027300000190734863. Also, 0.034 becomes 0.03400000184774399. I think `round` function can fix this. Did `or_beta` have a fixed number of digits after the decimal point in the original data? If 4 digits for example, `round(v, 4)` will fix.

**Comment by zigizolt** [comment]
Thank you, I changed the files according to your description. I chose 6 digits for or_beta as that seemed to be the most common in the original data (in general, the digit number varied around ~4-9  after the decimal point)

**Comment by rkimoakbioinformatics** [comment]
Thanks. It looks good, except one concern about or_beta. As there can be 9 digits after the decimal point, rounding at the 6th digit may result in a different value than the original. For example, 0.000000123 will become 0. 

Let's use two columns or_beta_coeff and or_beta_exp, both USMALLINT type (unsigned 2 byte integer). FLOAT is 4 bytes, so they will take the same space. Since there are up to 9 digits after the decimal point, original or_beta can be multiplied by 1,000,000,000 to become integer. or_beta_exp will be 0 to 9. or_beta_coeff can be 0 to 65535 with USMALLINT. My impression is that up to 3 significant digits were used in or_beta. If so, USMALLINT will be able to house it.

I'm sorry that more changes will be needed to accommodate this change. Please let me know if you have a different solution or a question.

**Comment by zigizolt** [comment]
There are no or_beta values that have more than three 0-s after the decimal, eg 0.000532 is the max amount of 0-s. Will it still be an issue when rounding?

**Comment by rkimoakbioinformatics** [comment]
You mean, or_beta values are like:

0.123
0.0123
0.00123
0.000123
0.000123456
0.012345678
0.123456789

(up to 9 digits after the decimal point, no more than 3 zeros after the decimal point)? If that's the case, actually we can just store or_beta * 10^9 as INTEGER and gwas_catalog.py can divide the integer by 10^9. This way, the number will not change strangely.

**Comment by zigizolt** [comment]
Okay, I think this issue is a little complex. Not only are the or_beta values going weird but on further testing some of the p-values aswell (eg. 7E-10 turns into 7.000000000000001e-10 in one case). I have also found out that the or_beta column values in the GWAS catalog can be very high aswell, like 15744.726 for example, which turns into 1544.7255859375. 

Basically I think it is because of the separation/addition/conversion of the numbers from integer to float etc during the pipeline. Apparently floating point numbers especially can cause precision errors. In my mind the boilerplate solution would be to treat the numbers as strings or use some type of math module to keep the numbers' precision but I don't know. It is also very strange that some of the time the values are correct and in other they are not...

**Comment by rkimoakbioinformatics** [comment]
Indeed it is a difficult problem. For example, https://www.geeksforgeeks.org/floating-point-error-in-python/. I think round would be the best bet then, but rounding at the 9th digit. Your thought?

**Comment by zigizolt** [comment]
Yes I think for or_beta rounding at the 9th digit works. For scientific notation I was thinking of adding g formatting to fix the trailing number issue. example output:

```python
Original p_value: 7.000000000000001e-10
Formatted p_value: 7e-10
Original or_beta: 0.021900000050663948
Rounded or_beta: 0.0219
Original p_value: 5.9999999999999996e-36
Formatted p_value: 6e-36
Original or_beta: 0.04670000076293945
Rounded or_beta: 0.046700001
``` 

or e formatting in which case the p-values would be 7.00e-10 and 6.00e-36

**Comment by rkimoakbioinformatics** [comment]
That sounds good. Please make such a change to the PR.

**Comment by zigizolt** [comment]
Hey, I have made the commits. Thank you!

**Comment by rkimoakbioinformatics** [comment]
It has been merged. Thanks for the great job. It'll be published soon.

**Pull request merged**
