### PR TITLE
Parquet reporter

### PR DESCRIPTION
**Pull request by AkRampersad**
This a Pull request (PR) I believe with all the aforementioned changes from the pivotal tracker story (updated .yml, updated file name and with chunking, formatted with py.black)

### CODE REVIEW

**Comment by rkimoakbioinformatics** [comment]
Looks like working. One more change is needed - at the end of `end` function, change `savepath` to be a list of all parquet files created by the reporter.

**Comment by AkRampersad** [comment]
Would you like the exact location (as in home/user/exampleinput0.parquet)
or just the file name (exampleinput0.parquet).

**Comment by rkimoakbioinformatics** [comment]
Full paths (exact locations)

**Comment by rkimoakbioinformatics** [comment]
The purpose of that variable is to let the users know what files are generated where.

**Comment by AkRampersad** [comment]
Okay that was the way i did it.I am commiting right now

**Comment by AkRampersad** [comment]
The change has been pushed.

**Pull request merged**
