### PR TITLE
Test scripts

### PR DESCRIPTION
**Pull request by sinmojito**
SPDI notation v0.0.2

- Refactored spdi.py to separate Variant classification and conversion in the separate `scripts` directory. 
- Added test cases for available classification and conversion scripts based on pytest.
- Added Unclassified variant classification to handle edge cases in future testing scenarios better. 
- Added input and key to the `tests` directory.
- Added contextual allele logic for Single and multi-nucleotide insertions and deletions. 
- Included logfile which contains relevant print statements to check the conversion logic. 
- Included a successfully annotated exampleinput.sqlite file.

### CODE REVIEW

**Comment by sinmojito** [comment]
I realized that I had put input and key and other tests in `tests` folder. I moved input and key to `test` and the pytest scripts remain in `tests`. 
`ov util test -m spdi` shows ` spdi: PASS`

**Comment by sinmojito** [comment]
Fyi, the scripts have a bunch of print statements in them for easy debugging and (manually) creating a log file to inspect any issues. So once you have tested and want me to push our print-less version so as not to clog up the user's terminal, I can edit them out and push that version.

**Comment by rkimoakbioinformatics** [comment]
Does this PR have the same py, md, and yml files as the other PR on spdi? If so, please close the other PR so that we can have only one PR for one module.

**Comment by rkimoakbioinformatics** [comment]
Also, please include at least one real variant for each variant category (those categories in the "scripts" folder), in the `input` file, and update `key` file after manual inspection of the SPDI output. The variants in the current `input` file can be left there or omitted to save manual inspection, as long as each variant category is covered in the `input` file.

**Comment by rkimoakbioinformatics** [comment]
Just in case, this is how I would find test variants:

- Go to the UCSC Genome Browser.
- Go to a random coordinate, such as chr1:9893854.
- Zoom in and out as necessary, and pan left or right to manually find a region which will meet a test category.

Usually, it is easier than we may think. Hope this helps.

**Pull request merged**
